### ISSUE TITLE
Stuck on start

### ISSUE THREAD

**Issue by t09m** [HeIp/CharlesHack#1]
v 4.1.4 won't get past the "Loading Preferences". 
![screen shot 2017-09-24 at 21 25 50](https://user-images.githubusercontent.com/1760563/30785971-0d1a4a08-a16f-11e7-9785-765b413af947.png)

**Comment by t09m** [comment]
Tried to open ./Charles in /Applications/Charles.app/Contents/MacOS and got: 

`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/xk72/charles/gIbD has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at com.xk72.lib.vIQL.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.xk72.charles.Main.xUFT(Unknown Source)
        at com.xk72.charles.gui.Main.main(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.xk72.charles.gui.transaction.viewers.protobuf.Xpfn.xUFT(Unknown Source)
        at com.xk72.charles.gui.MainWithClassLoader.main(Unknown Source)
        at com.xk72.charles.macos.gui.Main.main(Unknown Source)

`
